<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE biblioteca[
    <!ELEMENT biblioteca (libros*,revistas*,periodicos*)>


    <!ELEMENT libros (tituloL,indice,sinopsis,capitulos+)>
    <!ELEMENT indice (#PCDATA)>
    <!ELEMENT tituloL (#PCDATA)>
    <!ELEMENT capitulos (#PCDATA)>
   
    <!ELEMENT sinopsis (#PCDATA)>

    <!ATTLIST libros id CDATA #REQUIRED>
    <!ATTLIST libros tipo_clase CDATA #REQUIRED>
    <!ATTLIST libros numero_paginas_libro CDATA #REQUIRED>
    <!ATTLIST capitulos numero_paginas_cap CDATA #REQUIRED>

    <!ELEMENT revistas (tituloR,numero_de_revista,indice_de_contenido,seccionesR+)>
    <!ELEMENT tituloR (#PCDATA)>
    <!ELEMENT numero_de_revista (#PCDATA)>
    <!ELEMENT indice_de_contenido (#PCDATA)>
    <!ELEMENT seccionesR (numero_paginas,titulo_seccion)>
    <!ELEMENT titulo_seccion (#PCDATA)>

    <!ATTLIST revista id CDATA #REQUIRED>
    <!ATTLIST revista tipo_clase CDATA #REQUIRED>
    <!ATTLIST revista numero_paginas CDATA #REQUIRED>
    <!ATTLIST seccionesR numero_paginas CDATA #REQUIRED>
    <!ATTLIST seccionesR contenido CDATA #REQUIRED>


    <!ELEMENT periodicos (indiceP,seccionesP+)>
    <!ELEMENT seccionesP (articulos+)>
    <!ELEMENT indiceP (#PCDATA)>

    <!ATTLIST periodico id CDATA #REQUIRED>
    <!ATTLIST periodico tipo_clase CDATA #REQUIRED>
    <!ATTLIST periodico fecha CDATA #REQUIRED>
    <!ATTLIST seccionesP tipo CDATA #REQUIRED>
    <!ATTLIST articulos autor CDATA #REQUIRED>
]>


<biblioteca>
    <libros id="L0001" tipo_clase="Novela" numero_paginas_libro="120">
        <tituloL>titulo</tituloL>
        <indice>indice</indice>
        <sinopsis>sinopsis</sinopsis>
        <capitulos numero_paginas_cap="20">capitulo1</capitulos>

    </libros>
</biblioteca>
