<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!-- Vamos a elaborar una estructura de base de datos en XML que permita almacenar los datos de una biblioteca
en la red. Para ello se pide que elabores un DTD que permita validar los documentos XML con las siguientes 
características:

Existen tres tipos de documentos almacenados en la biblioteca: libros, revistas y periódicos. Todos 
los documentos están identificados por el atributo Id.
    Para los libros este atributo empieza con la letra “L” seguido de 4 dígitos identificativos.
    Para los periódicos este atributo empieza por la letra “P” seguido de los 4 dígitos identificativos.
    En el caso de las revistas empieza por la letra “R”.

Los libros a su vez son clasificados en novela, infantil o didáctico. Cada libro contiene un atributo 
identificativo de su clase denominado tipo_clase. Dentro de cada libro se tiene un título, varios
capítulos con el título en su interior, un índice y una sinopsis. Tanto en libro como en capítulo 
existe un atributo que contiene el número de páginas del libro o del capítulo, según corresponda. 
Cada capítulo contiene un elemento denominado contenido, en el que se tiene un atributo con el enlace a 
la información.

Las revistas a su vez son clasificadas en: informática, corazón, coches, investigación y otras.
Cada revista tiene el atributo tipo_clase identificativo de la clase a la que pertenece. Dentro de cada 
revista tenemos el título, el número de la revista, un índice de contenido y las secciones. En cada sección 
y en la revista se tiene un atributo que contiene el número de páginas. Además, en cada sección se tiene la
parte denominada contenido, en la que se tiene un atributo con un enlace a la información. De igual forma 
que en los anteriores, la última etiqueta del árbol debe ser el contenido con un atributo que referencia al
econtenido.

Los periódicos se clasifican en nacionales e internacionales. Cada periódico contiene el atributo tipo_clase 
identificativo de la clase a la que pertenece y un atributo que incluye la fecha de publicación.
Dentro de los periódicos tenemos secciones y un índice. Cada sección debe contener un atributo identificativo
del tipo de sección, que puede ser: económica, opinión, deportes, nacional o internacional. Las secciones
se dividen en artículos, en donde se define en un atributo el autor. Finalmente, el contenido será el último 
elemento del árbol, que necesita un atributo que referencie a la información.-->

 <!DOCTYPE biblioteca[
   <!ELEMENT biblioteca (documento+)>

   <!ELEMENT documento (libro|revista|periodico)>
   <!ATTLIST documento id ID #REQUIRED>

   <!ELEMENT libro (titulo, capitulo+,indice, sinopsis)>
   <!ATTLIST libro tipo_clase (novela|infantil|didactico) #REQUIRED>
   <!ATTLIST libro numero_paginas CDATA #REQUIRED>
   <!ELEMENT revista (titulo, numero, indice, seccion_revista+)>
   <!ATTLIST revista tipo_clase (informatica|corazon|coches|investigacion|otra) #REQUIRED>
   <!ATTLIST revista numero_paginas CDATA #REQUIRED>
   <!ELEMENT periodico (seccion_periodico+, indice)>
   <!ATTLIST periodico tipo_clase (nacional|internacional) #REQUIRED>
   <!ATTLIST periodico fecha_publicacion CDATA #REQUIRED>

   <!ELEMENT titulo (#PCDATA)>
   <!ELEMENT capitulo (titulo_capitulo, contenido)>
   <!ATTLIST capitulo numero_paginas CDATA #REQUIRED>
   <!ELEMENT indice (#PCDATA)>
   <!ELEMENT sinopsis (#PCDATA)>
   <!ELEMENT numero (#PCDATA)>
   <!ELEMENT seccion_revista (contenido)>
   <!ATTLIST seccion_revista numero_paginas CDATA #REQUIRED>
   <!ELEMENT seccion_periodico (articulo+)>
   <!ATTLIST seccion_periodico tipo_seccion (economica|opinion|deportes|nacional|internacional) #REQUIRED>


   <!ELEMENT titulo_capitulo (#PCDATA)>
   <!ELEMENT articulo (contenido)>
   <!ATTLIST articulo autor CDATA #REQUIRED>
   
   <!ELEMENT contenido (#PCDATA)>
   <!ATTLIST contenido enlace CDATA #REQUIRED>   
    
  
 ]>

<biblioteca>
   <documento id="L0001">
      <libro tipo_clase="novela" numero_paginas="350">
         <titulo> El pajaro carpintero</titulo>
         <capitulo numero_paginas="10">
            <titulo_capitulo>El comienzo</titulo_capitulo>
            <contenido enlace="https://www.w3schools.com/xml/xml_dtd_attributes.asp">Aqui va un contenido o vacio, hay que preguntarlo</contenido>
         </capitulo>
         <capitulo numero_paginas="20">
            <titulo_capitulo>El segundo</titulo_capitulo>
            <contenido enlace="https://www.w3schools.com/xml/xml_dtd_attributes.asp">Aqui va un contenido o vacio, hay que preguntarlo</contenido>
         </capitulo>
         <indice>
            1- El comienzo   pagina 4 
            2- El segundo    pagina 11
         </indice>
         <sinopsis>
            El libro trata sobre la exclavitud en América</sinopsis>
      </libro>
   </documento>
   <documento id="L0002">
      <libro tipo_clase="novela" numero_paginas="360">
         <titulo> El pajaro carpintero 2</titulo>
         <capitulo numero_paginas="12">
            <titulo_capitulo>El comienzo 2</titulo_capitulo>
            <contenido enlace="https://www.w3schools.com/xml/xml_dtd_attributes.asp">Aqui va un contenido o vacio, hay que preguntarlo</contenido>
         </capitulo>
         <capitulo numero_paginas="22">
            <titulo_capitulo>El segundo 2 </titulo_capitulo>
            <contenido enlace="https://www.w3schools.com/xml/xml_dtd_attributes.asp">Aqui va un contenido o vacio, hay que preguntarlo</contenido>
         </capitulo>
         <indice>
            1- El comienzo   pagina 4 
            2- El segundo    pagina 13
         </indice>
         <sinopsis>
            Segunda parte del libro que trata sobre la exclavitud en América</sinopsis>
      </libro>
   </documento>
   <documento id="R0001">
      <revista tipo_clase="investigacion" numero_paginas="21">
         <titulo>Ciencia e investigacion</titulo>
         <numero>1</numero>
         <indice> 
            1- Primera seccion   pagina 1 
            2- Segunda seccion    pagina 11
         </indice>
         <seccion_revista numero_paginas="10">
            <contenido enlace="https://www.w3schools.com/xml/xml_dtd_attributes.asp">Es el contenido de la primera seccion</contenido>
         </seccion_revista> 
         <seccion_revista numero_paginas="11">
            <contenido enlace="https://www.w3schools.com/xml/xml_dtd_attributes.asp">Es el contenido de la segunda seccion</contenido>
         </seccion_revista>
      </revista>
   </documento>
   <documento id="P0001">
      <periodico tipo_clase="nacional" fecha_publicacion="01/05/2021">
         <seccion_periodico tipo_seccion="nacional">
            <articulo autor="Ana Perez">
                <contenido enlace="https://www.w3schools.com/xml/xml_dtd_attributes.asp">Articulo sobre las elecciones de Madrid</contenido>
            </articulo>
            <articulo autor="Ana Perez">
                <contenido enlace="https://www.w3schools.com/xml/xml_dtd_attributes.asp">El ERTE durante la Pandemia</contenido>
            </articulo>
         </seccion_periodico>
         <seccion_periodico tipo_seccion="internacional">
            <articulo autor="Antonio Jose Mistral">
               <contenido enlace="https://www.w3schools.com/xml/xml_dtd_attributes.asp">Articulo sobre la liberalizacion de las patentes</contenido>
            </articulo>
         </seccion_periodico>
         <indice>
            1- Elecciones Madrid   pagina 1 
            2- Liberalizacion patentes    pagina 4
         </indice>
      </periodico>
   </documento>
</biblioteca>